# Default values for rick-and-morty-api
replicaCount: 1

image:
  repository: rick-and-morty-app
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: rickandmorty.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Database configuration
database:
  type: sqlite  # sqlite or postgresql
  url: "sqlite:///./test.db"
  # For PostgreSQL:
  # url: "postgresql://user:password@postgresql:5432/rickmorty"

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Logging sidecar configuration
logging:
  enabled: true
  image:
    repository: fluent/fluent-bit
    tag: "1.9"
    pullPolicy: IfNotPresent
  config:
    outputs: |
      [OUTPUT]
        Name stdout
        Match *
    inputs: |
      [INPUT]
        Name tail
        Path /var/log/app/*.log
        Parser docker
        Tag app.*

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

# Pod security context
podSecurityContext:
  fsGroup: 1000
