# Default values for rick-and-morty-api
replicaCount: 1

image:
  repository: deodatus0101/rick-morty-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: / 
  hosts:
    - host: "rickandmorty.local"  
      paths:
        - path: /
          pathType: Prefix

# Database configuration (CLEANED)
database:
# "postgresql" -> use K8s secret
# "sqlite" -> DO NOT set env var, let Python choose fallback
  type: postgresql
  
# The name of the secret that Terraform created
  secretName: "rickmorty-db-creds"

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minRePlicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Logging sidecar configuration
logging:
  enabled: true
  image:
    repository: fluent/fluent-bit
    tag: latest
    pullPolicy: IfNotPresent
  
  # Configuration for the fluent-bit.conf ConfigMap
  config:
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/app/*.log
    outputs: |
      [OUTPUT]
          Name stdout
          Match *
