apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rick-and-morty-api.fullname" . }}
  labels:
    {{- include "rick-and-morty-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rick-and-morty-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rick-and-morty-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.database.url | quote }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/app
        
        {{- if .Values.logging.enabled }}
        # Log collection sidecar
        - name: logging-sidecar
          image: "{{ .Values.logging.image.repository }}:{{ .Values.logging.image.tag }}"
          imagePullPolicy: {{ .Values.logging.image.pullPolicy }}
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/app
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        {{- end }}
      
      volumes:
        - name: log-volume
          emptyDir: {}
        
        {{- if .Values.logging.enabled }}
        - name: fluent-bit-config
          configMap:
            name: {{ include "rick-and-morty-api.fullname" . }}-fluent-bit-config
        {{- end }}
