{{- if eq .Values.database.type "postgresql" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rick-and-morty-api.fullname" . }}-db-credentials
  labels:
    {{- include "rick-and-morty-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url }}
{{- end }}
