name: SRE App CI/CD Pipeline

on:
  # Run on pushes to the main branch
  push:
    branches:
      - main
  # Also run on Pull Requests targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  # --- JOB 1: LINT & TEST ---
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 3. Install all dependencies
        run: pip install -r requirements-dev.txt

      - name: 4. Run Linter (Ruff)
        run: ruff check app/ tests/

      - name: 5. Run Unit Tests
        run: python -m pytest -m unit

      - name: 6. Run Integration Tests
        run: python -m pytest -m integration

  # --- JOB 2: BUILD & PUSH DOCKER IMAGE ---
  build-push:
    name: Build & Push Image
    runs-on: ubuntu-latest
    
    # --- IMPORTANT: Reference the PROD environment ---
    # This ensures the job can access secrets defined in that environment
    environment: PROD 

    needs: lint-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 3. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 4. Log in to Docker Hub
        # --- UPDATED: Using DOCKER_USER and DOCKER_TOKEN ---
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }} # Use the Access Token here

      - name: 5. Build and push image
        uses: docker/build-push-action@v6
        with:
          context: . 
          file: ./Dockerfile 
          push: true 
          tags: |
            # --- UPDATED: Using DOCKER_USER for image tag ---
            ${{ secrets.DOCKER_USER }}/rick-morty-sre-app:latest
            ${{ secrets.DOCKER_USER }}/rick-morty-sre-app:${{ github.sha }}
          platforms: linux/amd64 
